#!/bin/bash
HERE="$(dirname "$(readlink -f "$0")")"
export PATH="$HERE/usr/bin:$PATH"
export LD_LIBRARY_PATH="$HERE/usr/lib:$LD_LIBRARY_PATH"
export QML2_IMPORT_PATH="$HERE/usr/qml"
export QT_QPA_PLATFORM=xcb
export QT_QPA_PLATFORMTHEME=
exec "$HERE/usr/bin/QtSerialAssist" "$@"
